[package]
name = "richard/bfi"
version = "0.0.0"
description = "brainfuck wasm interpreter"
readme = "README.md"
repository = "https://github.com/richardanaya/watson/examples/bfi"

[[module]]
name = "bfi"
source = "bfi.wasm"
abi = "wasi"

[[command]]
name = "bfi"
module = "bfi"
