[package]
name = "richard/bf"
version = "0.0.0"
description = "brainfuck to wasm compiler"
readme = "README.md"
repository = "https://github.com/richardanaya/watson/examples/bf"

[[module]]
name = "bf"
source = "bf.wasm"
abi = "wasi"

[[command]]
name = "bf"
module = "bf"
