[package]
name = "wq"
version = "0.0.0"
authors = ["Richard Anaya"]
edition = "2018"
license = "MIT OR Apache-2.0"
categories = ["wasm", "cli"]
repository = "https://www.github.com/richardanaya/watson/examples/wq"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
watson = "0.3.2"
colored = "1.9"
